Auto Gen wrkflow
confluentinc/confluent-kubernetes-examples pull request #32
Opened 2021-06-22 12:31 UTC by MosheBlumbergX

I've added an auto gen workflow outlining how to use the auto gen certificates

2021-06-30 05:37 UTC, rohit2b requested changes
Suggested two changes, apart from that looks good!

2021-06-30 05:37 UTC, rohit2b commented on security/production-secure-deploy-auto-gen-certs/README.rst
> +In this deployment scenario, we will set this up, choosing SASL/Plain for authentication, using user provided CA certificate, CFK will auto generate the components certificates for you.
Suggest changing this text to:

In this deployment scenario, we'll choose SASL/Plain for authentication and configure TLS encryption using CFK auto-generated component certificates. 
You'll need to provide a certificate authority certificate for CFK to auto-generate the component certificates.

2021-06-30 05:37 UTC, rohit2b commented on security/production-secure-deploy-auto-gen-certs/README.rst
> +* CA private key and TLS Certificates
Change text to:

* Certificate authority - private key and certificate

2021-07-01 16:01 UTC, MosheBlumbergX commented
https://github.com/confluentinc/confluent-kubernetes-examples/pull/43 new pull

2021-07-01 16:01 UTC, closed without merging