Control Center and LDAP Auth, no RBAC
confluentinc/confluent-kubernetes-examples pull request #37
Opened 2021-06-28 15:42 UTC by MosheBlumbergX

Added scenario for Control Center and LDAP Auth, no RBAC

LDAP server was added groups and couple of users.

2021-06-28 15:42 UTC, MosheBlumbergX commented
@rohit2b @xnulinu

2021-06-30 04:27 UTC, rohit2b requested changes
Thanks for putting this together! I went through the scenario, and suggested a few fixes.

2021-06-30 04:27 UTC, rohit2b commented on security/plaintext-ldap-auth-control-Center/README.rst
> +In this workflow scenario, you'll set up a simple non-secure (no TLS) with Control Center LDAP authentication Confluent Platform, consisting of all components.
```suggestion
In this workflow scenario, you'll set up Control Center with LDAP based authentication to monitor and connect to a Confluent Platform with no security.
```
```suggestion
In this workflow scenario, you'll set up a simple non-secure (no TLS) with Control Center LDAP authentication Confluent Platform, consisting of all components.
```

2021-06-30 04:27 UTC, rohit2b commented on security/plaintext-ldap-auth-control-Center/README.rst
> +#. Deploy Confluent For Kubernetes.
Flip the order to match what's in the sections.

```suggestion
#. Deploy Confluent For Kubernetes.

#. Deploy LDAP server
```

2021-06-30 04:27 UTC, rohit2b commented on security/plaintext-ldap-auth-control-Center/README.rst
> +    Full Control: Username:Jame Password:james-sceret
is this `james` and `james-secret` ?

2021-06-30 04:27 UTC, rohit2b commented on security/plaintext-ldap-auth-control-Center/README.rst
> +    Restricted Control: Username:alice Password:alice-sceret
is this `alice-secret` ?

2021-06-30 04:27 UTC, rohit2b commented on security/plaintext-ldap-auth-control-Center/README.rst
> +  kubectl delete -f $TUTORIAL_HOME/confluent-platform-ccc-ldap.yamll --namespace=confluent
```suggestion
  kubectl delete -f $TUTORIAL_HOME/confluent-platform-ccc-ldap.yaml --namespace=confluent
```

2021-06-30 08:48 UTC, MosheBlumbergX commented
Thanks @rohit2b , much appreciated !

2021-06-30 18:58 UTC, rohit2b requested changes
One more fix, then done!

2021-06-30 18:58 UTC, rohit2b commented on security/plaintext-ldap-auth-control-Center/README.rst
> +    Full Control: Username:james Password:-secret
```suggestion
    Full Control: Username:james Password:james-secret  
```

2021-06-30 18:59 UTC, rohit2b approved these changes
I made the one tiny fix. This is good to go!

2021-06-30 19:00 UTC, merged