Repl ccloud to cloud
confluentinc/confluent-kubernetes-examples pull request #55
Opened 2021-07-28 15:42 UTC by MosheBlumbergX

Workflow for confluent cloud to confluent cloud replication with control center in the background to look at the Monitoring Extension metrics.

2021-07-28 15:42 UTC, MosheBlumbergX commented
@rohit2b  , can you check this one out please?

2021-07-29 05:46 UTC, rohit2b requested changes
Added one suggestion to start the README. Apart from that, this looks good!

2021-07-29 05:46 UTC, rohit2b commented on hybrid/replicator-cloud2cloud/README.md
> +
Let's add a high level description text at the start of what the user is able to achieve with this.

> You will be able to replicate data from one source Confluent Cloud cluster to a destination Confluent Cloud cluster, using Confluent Replicator. 
> You'll be able to monitor the end to end architecture through a single view in Confluent Control Center -> the source cluster, destination cluster, and the replication service.

And then add the details of what will be set up to accomplish this goal.

2021-07-29 09:29 UTC, MosheBlumbergX commented on hybrid/replicator-cloud2cloud/README.md
> +
thanks @rohit2b , now added.

2021-07-29 13:30 UTC, rohit2b approved these changes
LGTM!

2021-07-29 13:30 UTC, merged